index:
    path: /
    controller: App\Controller\StaticController::index

contact:
    path: /contact
    controller: App\Controller\StaticController::contact

ajoutTheme:
    path: /ajoutTheme
    controller: App\Controller\StaticController::ajoutTheme

listeThemes:
    path: /listeThemes
    controller: App\Controller\StaticController::listeThemes

modifThemes:
    path: /modifThemes
    controller: App\Controller\StaticController::modifThemes